name: groco
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  side_navigation: ^1.0.4
  provider: ^6.0.3
  syncfusion_flutter_charts: ^23.1.42
  http: ^1.1.0

  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/appIcon.png"
flutter:
  uses-material-design: true
  assets:
   - assets/images/
  fonts:
    - family: AlfaSlab
      fonts:
        - asset: assets/fonts/AlfaSlabOne-Regular.ttf
